project:
  type: book
  output-dir: docs

book:
  title: "CASA0025 Group Project: Cranes in transit"
  author: "SQLixirs"
  date: "2025-04-27"
  
  navbar:
     logo: "logo.png"
     collapse: true
     collapse-below: lg
     background: dark
     search: true
     right:
      - icon: github
        href: https://github.com/LZQ407/CASA0025_Project_Template
        
  sidebar:
    logo: "logo.png"
    title: "Cranes in transit"
    style: floating
    reader-mode: true
    collapse: true
    pinned: false
  
  chapters:
    - index.qmd
  repo-actions: [edit]
  sharing: [twitter, facebook]
  favicon: "favicon.ico"

format:
  html:
    toc: true
    toc-location: right
    toc-depth: 2
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai.theme
    linkcolor: "#34a832"
  
  

